/* Action types */
export const actionTypes = {
  USER_CHANGE_SEARCH_TEXT: 'USER/CHANGE_SEARCH_TEXT',
  USER_FETCH: 'USER/USER_FETCH',
  USER_FETCH_SUCCESS: 'USER/USER_FETCH_SUCCESS',
  USER_FETCH_FAIL: 'USER/USER_FETCH_SUCCESS_FAIL'
}
